spring:
  application:
    name: Cloud-Gateway
  profiles:
    include:
      - eureka
      - tomcat
      - zull
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration