spring:
  cloud:
    gateway:
      # 定义路由转发规则
      routes:
        - id: Cloud-Auth # 路由ID
          # 路由的目标地址，可以指定为HTTP地址，也可以通过lb://{微服务名称}来指定。lb为load balance的缩写，微服务名称为注册中心中对应的微服务名称。比如将uri配置为lb://Cloud-Auth的含义是，满足转发条件后，请求将均衡的转发到Cloud-Auth微服务上
          uri: lb://Cloud-Auth
          # 就是上面所说的谓词工厂。值为- Path=/auth/**表示请求Path以/auth开头的都会被匹配，然后转发到Cloud-Auth服务上
          predicates:
            - Path=/auth/**
          filters:
            # 通过- name: Hystrix指定添加Hystrix过滤器，通过name: authfallback指定HystrixCommandKey为authfallback，fallbackUri指定了回退的重定向地址
            - name: Hystrix
              args:
                name: authfallback
                fallbackUri: forward:/fallback/Cloud-Auth
        - id: Server-System
          uri: lb://Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/Server-System
        - id: Server-test
          uri: lb://Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/Server-Test
      # 为过滤器工厂，配置为- StripPrefix=1的意思是，请求转发前，将Path的内容截去前面一位。比如/auth/hello会被截取为/hello
      default-filters:
        - StripPrefix=1