spring:
  application:
    name: Server-System
  profiles:
    include:
      - eureka
      - tomcat
      - security
      -
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration