spring:
  boot:
    admin:
      client:
        url: http://${febs-monitor-admin}:8401
        username: cloud
        password: 123456

# 配置了SBA客户端的名称，描述和版本信息；
info:
  app:
    name: ${spring.application.name}
    description: "@project.description@"
    version: "@project.version@"

management:
  endpoints:
    web:
      exposure:
        ## 表示将SBA客户端的所有监控端点都暴露给SBA服务端
        include: '*'
  endpoint:
    health:
      ## 表示总是展示详细的健康信息
      show-details: ALWAYS