spring:
  application:
    name: Server-System
  profiles:
    include:
      - eureka
      - tomcat
      - security
      - datasource
      - mybatis
      - monitor
      - rabbitmq
      - zipkin

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration