spring:
  boot:
    admin:
      client:
        url: http://localhost:8401
        username: cloud
        password: 123456

management:
  endpoints:
    web:
      exposure:
        ## 表示将SBA客户端的所有监控端点都暴露给SBA服务端
        include: '*'
  endpoint:
    health:
      ## 表示总是展示详细的健康信息
      show-details: ALWAYS