spring:
  application:
    name: Server-Test
  profiles:
    include:
      - eureka
      - tomcat
      - security
      - monitor
      - feign
      - rabbitmq
      - zipkin

  # 关闭多数据源自动装配
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceAutoConfiguration